swagger: "2.0"
info:
  description: "This is a Compare two strings. "
  version: "1.0.0"
  title: "Swagger String similarities"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "api.sample.site"
basePath: "/v1"
tags:
- name: "String similarities"
  description: "Compare two string and get the similarities"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /compare-two-strings:
    post:
      tags:
      - "compare-two-string"
      summary: "Compare similarities from two string "
      description: ""
      operationId: "compareTwoStrings"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: " Two string that we need to use for comparison"
        required: true
        schema:
          $ref: "#/definitions/PayLoad"
      responses:
        "400":
          description: "Invalid input"
definitions:
  PayLoad:
    properties:
      text_one:
        description: "First String "
        example: "This is the sample one text"
        type: "string"
      text_two:
        description: "First String "
        example: "This is the sample one text"
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"